---
- name: Spin up Codius Host images
  hosts: localhost
  connection: local
  vars:
    regions:
      - region: eu-west-1
        key: codius-host-ireland
        image: ami-934ecc4e
        vpc_subnet: subnet-235eca46
        vpc: vpc-f2f52b97
      - region: us-east-1
        key: codius-host-virginia
        image: ami-84562dec
        vpc_subnet: subnet-8c9026d5
        vpc: vpc-86abdfe3
      - region: us-west-2
        key: codius-host-oregon
        image: ami-23ebb513
        vpc_subnet: subnet-a38a2cd4
        vpc: vpc-b3da73d6
      - region: us-west-1
        key: codius-host-california
        image: ami-56120b13
        vpc_subnet: subnet-c7d2cc81
        vpc: vpc-6168ae04
      - region: eu-central-1
        key: codius-host-frankfurt
        image: ami-9c380b81
        vpc_subnet: subnet-eee40795
        vpc: vpc-74e41b1d
      - region: ap-southeast-1
        key: codius-host-singapore
        image: ami-c2381390
        vpc_subnet: subnet-d1db04b4
        vpc: vpc-66fa0103
      - region: ap-northeast-1
        key: codius-host-tokyo
        image: ami-18b6aa19
        vpc_subnet: subnet-4cb14515
        vpc: vpc-a773bfc2
      - region: ap-southeast-2
        key: codius-host-sydney
        image: ami-b1eb9e8b
        vpc_subnet: subnet-f5805d90
        vpc: vpc-ead4138f
      - region: sa-east-1
        key: codius-host-sao-paulo
        image: ami-73f5496e
        vpc_subnet: subnet-ebe14c8e
        vpc: vpc-5539b730
  tasks:
    - name: Configure the codius-host security group
      with_items: regions
      ec2_group:
        state: present
        description: Runs Codius Host on 443
        name: codius-host
        region: "{{item.region}}"
        vpc_id: "{{item.vpc}}"
        rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
    - name: Spin up a codius host image
      with_items: regions
      ec2:
        region: "{{item.region}}"
        count_tag: runs_codius_host
        exact_count: 1
        key_name: "{{item.key}}"
        instance_tags:
          runs_codius_host: 1
        assign_public_ip: true
        group: codius-host
        instance_type: m1.medium
        image: "{{item.image}}"
        vpc_subnet_id: "{{item.vpc_subnet}}"
